apeiro_agency/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path(
        "",
        views.home_page_view,
        name="home",
    ),
    path(
        "categories/",
        views.category_list_view,
        name='category_list'
    ),
    path(
        "category/<slug:slug>/",
        views.category_detail_view,
        name='category_detail'
    )
]

apeiro_agency/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.add_to_basket,
        name='add_to_basket'
    ),
    path('cart/', views.manage_basket,
        name='cart'
    ),
]

config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    path("",
        include("services.urls", namespace='services')
    ),
    # User management
    path(
        "users/",
        include("apeiro_agency.users.urls", namespace="users"),
    ),
    path('orders/', include('orders.urls', namespace='orders')),
    path("accounts/", include("allauth.urls")),
    path('api-auth/', include('rest_framework.urls')),
    path('api/services/', include('services.api_routes')),
    path('api/orders/', include('orders.api_routes')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns

apeiro_agency/core/models.py
from model_utils.models import TimeStampedModel

from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class PricingPlan(TimeStampedModel):
    title = models.CharField(max_length=50)
    monthly_price = models.PositiveIntegerField(
        blank=True,
        null=True
    )
    annual_price = models.PositiveIntegerField(
        blank=True,
        null=True
    )
    ontime_pay = models.PositiveIntegerField(
        blank=True,
        null=True
    )

    class Meta:
        ordering = ('title',)

    def __str__(self):
        s = f'{self.title}, '
        if self.monthly_price:
            s += f'monthly: {self.monthly_price} '
        if self.annual_price:
            s += f'annual: {self.annual_price} '
        if self.ontime_pay:
            s += f'onetime: {self.ontime_pay}'
        return s.strip()


class FeatureItem(TimeStampedModel):
    feature_key = models.CharField(max_length=200)
    feature = models.CharField(max_length=200)

    class Meta:
        ordering = ('feature_key',)

    def __str__(self):
        return f'{self.feature_key} : {self.feature}'

apeiro_agency/core/views.py
from django.shortcuts import render
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView
)

from .models import ServiceCategory


class HomePageView(TemplateView):
    template_name = 'core/home.html'

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        featured_categories = ServiceCategory.objects.filter(
            is_featured=True
        )
        ctx['featured_categories'] = featured_categories
        return ctx

home_page_view = HomePageView.as_view()


class CategoryListView(ListView):
    model = ServiceCategory
    template_name = 'core/category_list.html'
    context_object_name = 'categories'

category_list_view = CategoryListView.as_view()


class CategoryDetailView(DetailView):
    model = ServiceCategory
    template_name = 'core/category_detail.html'
    context_object_name = 'category'
    slug_field = 'slug' 
    slug_url_kwarg = 'slug' 

category_detail_view = CategoryDetailView.as_view()

apeiro_agency/core/templates/core/category_detail.html
{% extends "base.html" %}

{% load static %}



{% block content %}
    <div class="container container-w-95 mb-5">
        <div class="page-header bg-warning">
            <div class="page-header--content d-flex justify-content-between align-items-center">
                <div class="page-header--title">
                    <h4 class="text-light">Services</h4>
                </div>
                <div class="page-header--breadcrumb">
                    <ul class="breadcrumb p-0 m-0 bg-transparent">
                        <li class="breadcrumb-item">
                            <a class="text-light small" href="">Home</a>
                        </li>
                        <li class="breadcrumb-item">
                            <a class="text-light small" href="">Categories</a>
                        </li>
                        <li class="breadcrumb-item small">
                            <a class="text-muted" href="">Services</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row" id="categories-section">
            <div class="col-lg-8">
                <!-- listview/gridview/filters -->
                <div class="listing-actions mr-4">
                    <div class="listing-actions--wrapper d-flex justify-content-between align-items-center">
                        <div class="listing-actions--left">
                            <a href="" class="text-dark mr-2 listing-action listing-action-active">
                                <i class="fas fa-th-list"></i>
                            </a>
                            <a href="" class="text-dark listing-action mr-2">
                                <i class="fas fa-th"></i>
                            </a>
                            <span class="text-muted small" id="listing-actions-result-summary">
                                Showing 1–9 of 16 results
                            </span>
                        </div>
                        <div class="listing-actions--right">
                            <form action="">
                                <select name="" id="">
                                    <option value="" selected>select an option</option>
                                    <option value="">Option 1</option>
                                    <option value="">Option 1</option>
                                    <option value="">Option 1</option>
                                    <option value="">Option 1</option>
                                </select>
                            </form>
                        </div>
                    </div>
                </div>
                
                <!-- category listing and pagination -->
                <div class="row mt-4 categories-row pr-4">
                    
                    {% for service in category.services.all %}
                        <div class="col-lg-4 mb-4">
                            <div class="category-card">
                                <div class="category-card-img">
                                    <img src="{{ category.image.url }}" alt="">
                                </div>
                                <div class="category-card-metadata text-center py-2">
                                    <a href="{{ category.get_absolute_url }}">
                                        <p>{{ service.name }}</p>
                                    </a>    
                                    <span class="text-muted">$2500</span>
                                </div>
                                <div class="category-card--actions">
                                    <a href='#' 
                                        data-category-id="{{ category.id }}"
                                        data-service-id="{{ service.id }}"
                                        class="btn btn-success mb-2 add-to-cart"
                                        click="addToCart()">
                                        Add to cart
                                    </a>
                                    <a href="{{ category.get_absolute_url }}" 
                                        class="btn btn-warning">Details
                                    </a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                    <!-- paginator -->
                    <div class="col-12 mt-5 py-4 top-border-5 border-light 
                        d-flex justify-content-center">
                        <nav aria-label="Page navigation">
                            <ul class="pagination custom-pagination">
                                <li class="page-item">
                                    <a class="page-link" href="#">
                                        <i class="fas fa-long-arrow-alt-left"></i>
                                    </a>
                                </li>
                                <li class="page-item active"><a class="page-link" href="#">1</a></li>
                                <li class="page-item"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item">
                                    <a class="page-link" href="#">
                                        <i class="fas fa-long-arrow-alt-right"></i>
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 pl-5">
                <div class="category-list-sidebar ">
                    <div class="sidegroup">
                        <div class="sidegroup--title mb-3">
                            <span class="halfline yellow-border"></span>
                            <h4>Cart</h4>
                        </div>
                        <div class="sidebar-cart">
                            <div class="sidebar-cart--cart-items">
                                <!-- Updated from JS -->
                            </div>
                            <div class="sidebar-cart--cart-metadata">
                                <div class="sidebar-cart--subtotal py-3 small">
                                    <p>Subtotal: $800</p>
                                </div>
                                <div class="sidebar-cart--actions">
                                    <a href="" class="btn btn-sm btn-warning">
                                        View Cart
                                    </a>
                                    <a href="" class="btn btn-sm btn-success">
                                        Checkout
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="mt-5">
        {% include 'partials/_footer.html' %}
    </div>
{% endblock content %}



{% block javascript %}
    <script>
        const listingActionBtns = document.querySelectorAll('.listing-action');
        let activeListingBtn = document.querySelector('.listing-action-active')
        var cartItemRmBtns = document.querySelectorAll('.cart-item-remover');
        const addToCartBtns = document.querySelectorAll('.add-to-cart');
        const sidebarCartItemsContainer = document.querySelector('.sidebar-cart--cart-items');

        (function() {
            fetch('{% url "get_basket_items" %}')
                .then((response) => response.json())
                .then((data) => {
                    data.forEach((item) => {
                        let str = '';
                        str += `
                        <div class="sidebarcart-item py-3 d-flex
                            align-items-center border-bottom">
                            <div id="rm-item-${item.service.id}" class="pointer cart-item-remover mr-3"
                                onclick="rmCartItem()">
                                <i class="fas fa-times"></i>
                            </div>
                            <div class="sidebarcart-item--img mr-3">
                                <img src="${item.service.icon}" alt=""
                                    width="65" height="65">
                            </div>
                            <div class="sidebarcart-item--info">
                                <p>${ item.service.name }</p>
                                <span class="text-muted">
                                    2 x $400
                                </span>
                            </div>
                        </div>
                        `;
                        sidebarCartItemsContainer.insertAdjacentHTML('beforeend', str);
                        cartItemRmBtns = document.querySelectorAll('.cart-item-remover');
                    })
                })
        })()
        
        function rmCartItem(){
            const elem = event.target.parentNode.parentNode;
            elem.remove();
        }

        function updateCartQuantityNav(){
            fetch('{% url "get_basket_count" %}')
                .then((response) => response.json())
                .then((data) => {
                    document.querySelector('.cartcount-number').textContent = data.basket_count;
                })
        }

        function updateCartSidebar(data, categoryId) {
            const url = `/api/core/category/${categoryId}`;
            fetch(url, {
                method: 'GET',
                }).then(function(response){
                    return response.json();
                }).then(function(data){
                    const newCartItem = `
                    <div class="sidebarcart-item py-3 d-flex
                        align-items-center border-bottom">
                        <div id="rm-item-${data.id}" class="pointer cart-item-remover mr-3"
                            onclick="rmCartItem()">
                            <i class="fas fa-times"></i>
                        </div>
                        <div class="sidebarcart-item--img mr-3">
                            <img src="${data.image}" alt=""
                                width="65" height="65">
                        </div>
                        <div class="sidebarcart-item--info">
                            <p>${ data.name }</p>
                            <span class="text-muted">
                                2 x $400
                            </span>
                        </div>
                    </div>
                    `;
                    sidebarCartItemsContainer.insertAdjacentHTML('beforeend', newCartItem);
                    cartItemRmBtns = document.querySelectorAll('.cart-item-remover');
                }).then(function(err){
                    console.log(err, 'FAILEDDDDDD');
                })
        }

        function addToCart(e) {
            e.preventDefault();
            const serviceID = this.dataset.serviceId;
            const categoryId = this.dataset.categoryId;
            let url = '{% url "orders:add_to_basket" %}?service_id=000'
            url = url.replace('000', serviceID)
            fetch(url)
            .then((response) => response.json())
            .then(function(data) {
                updateCartQuantityNav();
                updateCartSidebar(data, categoryId);
            })
        }

        listingActionBtns.forEach(function(actionItem){
            actionItem.addEventListener('click', function(e){
                activeListingBtn.classList.remove('listing-action-active');
                e.preventDefault();
                actionItem.classList.toggle('listing-action-active');
                activeListingBtn = actionItem;
            });
        });

        addToCartBtns.forEach(function(category){
            category.addEventListener('click', addToCart)
        });
    </script>
{% endblock javascript %}
    

apeiro_agency/core/templates/core/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <!-- banner part start -->
    <section id="banner_full">
        <div class="banner_item" 
            style="background: url({% static 'images/pexels-fauxels-3184465.jpg' %});">
            <div class="container p-lg-0">
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center">
                        <div class="banner_text">
                            <h1>The New Way To DesignYour Marketing Campaing</h1>
                            <p>Get your design done only based on your needs</p>
                            <a href="#">Learn More</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="banner_item" style="background: url({% static 'images/pexels-fauxels-3228711.jpg' %});">
            <div class="container p-lg-0">
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center">
                        <div class="banner_text">
                            <h1>The New Way To DesignYour Marketing Campaing</h1>
                            <p>Get your design done only based on your needs</p>
                            <a href="#">Learn More</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="banner_item" style="background: url({% static 'images/pexels-fauxels-3184665.jpg' %});">
            <div class="container p-lg-0">
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center">
                        <div class="banner_text">
                            <h1>The New Way To DesignYour Marketing Campaing</h1>
                            <p>Get your design done only based on your needs</p>
                            <a href="#">Learn More</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- banner part end -->

    <!-- Your identity part start -->
    <section id="identity_full">
        <div class="container p-lg-0">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="mt-5">
                        <h2>Browse Our Products</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="catagoys_btn">
                        <ul class="nav nav-pills mb-3 cl_menu" id="pills-tab" role="tablist">
                            {% for category in featured_categories %}
                                <li class="nav-item">
                                    <a class="nav-link text-light {% if forloop.counter == 1 %}active{% endif %}" 
                                        id="pills-{{ category.pk }}-tab" data-toggle="pill" 
                                        href="#{{ category.name|slugify }}_data" role="tab" aria-controls="pills-{{ category.pk }}" 
                                        aria-selected="true">
                                        <img src="{{ category.category_icon.url }}" alt="">
                                    </a>
                                </li>
                            {% endfor %}
                            <li>
                                <a href="{% url 'core:category_list' %}" class="maroff">View More Catagory</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Your identity part end -->

    <!-- newslatter part start -->
    <section id="newslatter_full">
        <div class="container p-lg-0">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="newaslatter_text">
                        <h4>Join Our Newsletter</h4>
                        <p>Enter your email and be the first to know about special offers, new arrivals and events!</p>
                        <form>
                            <input type="emnail" name="your-email" aria-required="true" placeholder="Enter Your Email">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- news latter part end -->
    
    <!-- Footer -->
    {% include 'partials/_footer.html' %}

{% endblock content %}

apeiro_agency/core/templates/core/products.html
{% extends "base.html" %}

{% load static %}



{% block content %}
<div class="container container-w-95 mb-5">
    <div class="page-header bg-warning">
        <div class="page-header--content d-flex justify-content-between align-items-center">
            <div class="page-header--title">
                <h4 class="text-light">Categories</h4>
            </div>
            <div class="page-header--breadcrumb">
                <ul class="breadcrumb p-0 m-0 bg-transparent">
                    <li class="breadcrumb-item">
                        <a class="text-light small" href="">Home</a>
                    </li>
                    <li class="breadcrumb-item small">
                        <a class="text-light" href="">Categories</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row" id="categories-section">
        <div class="col-lg-8">
            <!-- listview/gridview/filters -->
            <div class="listing-actions mr-4">
                <div class="listing-actions--wrapper d-flex justify-content-between align-items-center">
                    <div class="listing-actions--left">
                        <a href="" class="text-dark mr-2 listing-action listing-action-active">
                            <i class="fas fa-th-list"></i>
                        </a>
                        <a href="" class="text-dark listing-action mr-2">
                            <i class="fas fa-th"></i>
                        </a>
                        <span class="text-muted small" id="listing-actions-result-summary">
                            Showing 1–9 of 16 results
                        </span>
                    </div>
                    <div class="listing-actions--right">
                        <form action="">
                            <select name="" id="">
                                <option value="" selected>select an option</option>
                                <option value="">Option 1</option>
                                <option value="">Option 1</option>
                                <option value="">Option 1</option>
                                <option value="">Option 1</option>
                            </select>
                        </form>
                    </div>
                </div>
            </div>

            <!-- category listing and pagination -->
            <div class="row mt-4 categories-row row-left-border pr-4">

                {% for category in categories %}
                <div class="col-lg-4 mb-4">
                    <div class="category-card">
                        <div class="category-card-img">
                            <img src="{{ category.image.url }}" alt="">
                        </div>
                        <div class="category-card-metadata text-center py-2">
                            <a class="d-block" href="{{ category.get_absolute_url }}">
                                <p>{{ category.name }}</p>
                                <span class="text-muted">$2500</span>
                            </a>
                        </div>
                        <div class="category-card--actions">
                            <button data-category-id="{{ category.id }}" class="btn btn-success mb-2 add-to-cart">Add to
                                cart
                            </button>
                            <a href="{{ category.get_absolute_url }}" class="btn btn-warning">Details
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}

                <!-- paginator -->
                <div class="col-12 mt-5 py-4 top-border-5 border-light 
                        d-flex justify-content-center">
                    <nav aria-label="Page navigation">
                        <ul class="pagination custom-pagination">
                            <li class="page-item">
                                <a class="page-link" href="#">
                                    <i class="fas fa-long-arrow-alt-left"></i>
                                </a>
                            </li>
                            <li class="page-item active"><a class="page-link" href="#">1</a></li>
                            <li class="page-item"><a class="page-link" href="#">2</a></li>
                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                            <li class="page-item">
                                <a class="page-link" href="#">
                                    <i class="fas fa-long-arrow-alt-right"></i>
                                </a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
        <div class="col-lg-4 pl-5">
            <div class="category-list-sidebar ">
                <div class="sidegroup">
                    <div class="sidegroup--title mb-3">
                        <span class="halfline yellow-border"></span>
                        <h4>Cart</h4>
                    </div>
                    <div class="sidebar-cart">
                        <div class="sidebar-cart--cart-items">
                            <!-- Managed By JS -->
                        </div>
                        <div class="sidebar-cart--cart-metadata">
                            <div class="sidebar-cart--subtotal py-3 small">
                                <p>Subtotal: $800</p>
                            </div>
                            <div class="sidebar-cart--actions">
                                <a href="" class="btn btn-sm btn-warning">
                                    View Cart
                                </a>
                                <a href="" class="btn btn-sm btn-success">
                                    Checkout
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Footer -->
<div class="mt-5">
    {% include 'partials/_footer.html' %}
</div>
{% endblock content %}



{% block javascript %}
<script>
    const listingActionBtns = document.querySelectorAll('.listing-action');
    let activeListingBtn = document.querySelector('.listing-action-active')
    var cartItemRmBtns = document.querySelectorAll('.cart-item-remover');
    const addToCartBtns = document.querySelectorAll('.add-to-cart');
    const sidebarCartItemsContainer = document.querySelector('.sidebar-cart--cart-items');
    const subtotalElem = document.querySelector('.sidebar-cart--subtotal p');

    function checknUpdateSubtotal() {
        if (sidebarCartItemsContainer.children.length <= 0) {
            subtotalElem.textContent = 'No items in the cart';
        } else {
            // show subtotal amount in the container element.
            subtotalElem.textContent = `Subtotal: $1000`;
        }
    }

    function rmCartItem() {
        const elem = event.target.parentNode.parentNode;
        elem.remove();
        checknUpdateSubtotal();
    }

    function addToCart() {
        categoryId = this.dataset.categoryId;
        const url = `/api/core/category/${categoryId}`;
        fetch(url, {
            method: 'GET',
        }).then(function (response) {
            return response.json();
        }).then(function (data) {
            const newCartItem = `
                <div class="sidebarcart-item py-3 d-flex
                    align-items-center border-bottom">
                    <div id="rm-item-${data.id}" class="pointer cart-item-remover mr-3"
                        onclick="rmCartItem()">
                        <i class="fas fa-times"></i>
                    </div>
                    <div class="sidebarcart-item--img mr-3">
                        <img src="${data.image}" alt=""
                            width="65" height="65">
                    </div>
                    <div class="sidebarcart-item--info">
                        <p>${data.name}</p>
                        <span class="text-muted">
                            2 x $400
                        </span>
                    </div>
                </div>
                `;
            sidebarCartItemsContainer.insertAdjacentHTML('beforeend', newCartItem);
            cartItemRmBtns = document.querySelectorAll('.cart-item-remover');
            checknUpdateSubtotal();
        }).then(function (err) {
            // console.log(err, 'FAILEDDDDDD');
        })
    }

    // table, grid view, range
    listingActionBtns.forEach(function (actionItem) {
        actionItem.addEventListener('click', function (e) {
            activeListingBtn.classList.remove('listing-action-active');
            e.preventDefault();
            actionItem.classList.toggle('listing-action-active');
            activeListingBtn = actionItem;
        });
    });

    addToCartBtns.forEach(function (category) {
        category.addEventListener('click', addToCart)
    });

    // IFEES
    (function () {
        checknUpdateSubtotal();
    })()
</script>
{% endblock javascript %}