apeiro_agency/services/urls.py
from django.urls import path
from . import views

app_name = 'services'

urlpatterns = [
    path(
        "",
        views.home_page_view,
        name="home",
    ),
    path(
        "categories/",
        views.category_list_view,
        name='category_list'
    ),
    path(
        "services/",
        views.service_list_view,
        name='service_list'
    ),
    path(
        "services/<slug:category>/",
        views.service_list_view,
        name='category_service_list'
    ),
]

config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    path("",
        include("services.urls", namespace='services')
    ),
    # User management
    path(
        "users/",
        include("apeiro_agency.users.urls", namespace="users"),
    ),
    path('orders/', include('orders.urls', namespace='orders')),
    path("accounts/", include("allauth.urls")),
    path('api-auth/', include('rest_framework.urls')),
    path('api/services/', include('services.api_routes')),
    path('api/orders/', include('orders.api_routes')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns

apeiro_agency/services/models.py
from model_utils.models import TimeStampedModel

from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

from core.models import FeatureItem, PricingPlan
from service_analytics.models import Impression


class ServiceCategory(TimeStampedModel):
    name = models.CharField(max_length=100, unique=True)
    category_icon = models.ImageField(
        upload_to='category_icons/',
        blank=True,
        default='category_icons/default.png'
    )
    image = models.ImageField(
        upload_to='category/',
        blank=True,
        default='category/default.jpg'
    )
    slug = models.SlugField(blank=True, null=True, unique=True)
    description = models.TextField(blank=True, null=True)
    is_featured = models.BooleanField(default=False)

    class Meta:
        ordering = ['name', '-created']
        verbose_name_plural = 'Service Categories'
    
    def get_absolute_url(self):
        return reverse(
            'services:category_service_list',
            args=(),
            kwargs={'slug': self.slug}
        )    
    
    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        update = kwargs.get('update', False)
        if not update:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class Service(TimeStampedModel):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(blank=True, null=True, unique=True)
    primary_image = models.ImageField(
        upload_to='services/primary-images/',
        blank=True,
        default='services/primary-images/default.jpg'
    )
    description = models.TextField(blank=True, null=True)
    vendor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='services',
        on_delete=models.CASCADE
    )
    features = models.ManyToManyField(
        FeatureItem,
        blank=True
    )
    pricing = models.ForeignKey(
        PricingPlan,
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )
    category = models.ForeignKey(
        ServiceCategory,
        on_delete=models.CASCADE,
        related_name='services'
    )
    is_verified = models.BooleanField(default=False)

    class Meta:
        ordering = ['name', '-created']
        verbose_name_plural = 'Services'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        update = kwargs.get('update', False)
        if not update:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class ServicePhoto(TimeStampedModel):
    image = models.ImageField(upload_to='services/images/')
    service = models.ForeignKey(Service,
        related_name='images',
        on_delete=models.CASCADE
    )

apeiro_agency/services/views.py
from django.db.models import Count
from django.shortcuts import render, get_object_or_404
from django.views.generic.base import TemplateResponseMixin, View
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView
)

from .models import ServiceCategory, Service


class HomePageView(TemplateView):
    template_name = 'services/home.html'

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        featured_categories = ServiceCategory.objects.filter(
            is_featured=True
        )
        ctx['featured_categories'] = featured_categories
        return ctx

home_page_view = HomePageView.as_view()


class ServiceListView(TemplateResponseMixin, View):
    model = Service
    template_name = 'services/products.html'

    def get(self, request, category=None):
        categories = ServiceCategory.objects.annotate(
            total_services=Count('services'))
        services = Service.objects.all()

        if category:
            category = get_object_or_404(ServiceCategory, slug=category)
            services = services.filter(category=category)
        return self.render_to_response({
            'categories': categories,
            'category': category,
            'services': services
        })

service_list_view = ServiceListView.as_view()

class CategoryListView(ListView):
    model = ServiceCategory
    template_name = 'services/category_list.html'
    context_object_name = 'categories'

category_list_view = CategoryListView.as_view()


class CategoryDetailView(DetailView):
    model = ServiceCategory
    template_name = 'services/category_detail.html'
    context_object_name = 'category'
    slug_field = 'slug' 
    slug_url_kwarg = 'slug' 

category_detail_view = CategoryDetailView.as_view()

apeiro_agency/services/templates/services/category_detail.html
{% extends "base.html" %}

{% load static %}



{% block content %}
    <div class="container container-w-95 mb-5">
        <div class="page-header bg-warning">
            <div class="page-header--content d-flex justify-content-between align-items-center">
                <div class="page-header--title">
                    <h4 class="text-light">Services</h4>
                </div>
                <div class="page-header--breadcrumb">
                    <ul class="breadcrumb p-0 m-0 bg-transparent">
                        <li class="breadcrumb-item">
                            <a class="text-light small" href="">Home</a>
                        </li>
                        <li class="breadcrumb-item">
                            <a class="text-light small" href="">Categories</a>
                        </li>
                        <li class="breadcrumb-item small">
                            <a class="text-muted" href="">Services</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row" id="categories-section">
            <div class="col-lg-8">
                <!-- listview/gridview/filters -->
                <div class="listing-actions mr-4">
                    <div class="listing-actions--wrapper d-flex justify-content-between align-items-center">
                        <div class="listing-actions--left">
                            <a href="" class="text-dark mr-2 listing-action listing-action-active">
                                <i class="fas fa-th-list"></i>
                            </a>
                            <a href="" class="text-dark listing-action mr-2">
                                <i class="fas fa-th"></i>
                            </a>
                            <span class="text-muted small" id="listing-actions-result-summary">
                                Showing 1–9 of 16 results
                            </span>
                        </div>
                        <div class="listing-actions--right">
                            <form action="">
                                <select name="" id="">
                                    <option value="" selected>select an option</option>
                                    <option value="">Option 1</option>
                                    <option value="">Option 1</option>
                                    <option value="">Option 1</option>
                                    <option value="">Option 1</option>
                                </select>
                            </form>
                        </div>
                    </div>
                </div>
                
                <!-- category listing and pagination -->
                <div class="row mt-4 categories-row pr-4">
                    
                    {% for service in category.services.all %}
                        <div class="col-lg-4 mb-4">
                            <div class="category-card">
                                <div class="category-card-img">
                                    <img src="{{ category.image.url }}" alt="">
                                </div>
                                <div class="category-card-metadata text-center py-2">
                                    <a href="{{ category.get_absolute_url }}">
                                        <p>{{ service.name }}</p>
                                    </a>    
                                    <span class="text-muted">$2500</span>
                                </div>
                                <div class="category-card--actions">
                                    <a href='#' 
                                        data-category-id="{{ category.id }}"
                                        data-service-id="{{ service.id }}"
                                        class="btn btn-success mb-2 add-to-cart"
                                        click="addToCart()">
                                        Add to cart
                                    </a>
                                    <a href="{{ category.get_absolute_url }}" 
                                        class="btn btn-warning">Details
                                    </a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                    <!-- paginator -->
                    <div class="col-12 mt-5 py-4 top-border-5 border-light 
                        d-flex justify-content-center">
                        <nav aria-label="Page navigation">
                            <ul class="pagination custom-pagination">
                                <li class="page-item">
                                    <a class="page-link" href="#">
                                        <i class="fas fa-long-arrow-alt-left"></i>
                                    </a>
                                </li>
                                <li class="page-item active"><a class="page-link" href="#">1</a></li>
                                <li class="page-item"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item">
                                    <a class="page-link" href="#">
                                        <i class="fas fa-long-arrow-alt-right"></i>
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 pl-5">
                <div class="category-list-sidebar ">
                    <div class="sidegroup">
                        <div class="sidegroup--title mb-3">
                            <span class="halfline yellow-border"></span>
                            <h4>Cart</h4>
                        </div>
                        <div class="sidebar-cart">
                            <div class="sidebar-cart--cart-items">
                                <!-- Updated from JS -->
                            </div>
                            <div class="sidebar-cart--cart-metadata">
                                <div class="sidebar-cart--subtotal py-3 small">
                                    <p>Subtotal: $800</p>
                                </div>
                                <div class="sidebar-cart--actions">
                                    <a href="" class="btn btn-sm btn-warning">
                                        View Cart
                                    </a>
                                    <a href="" class="btn btn-sm btn-success">
                                        Checkout
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="mt-5">
        {% include 'partials/_footer.html' %}
    </div>
{% endblock content %}



{% block javascript %}
    <script>
        const listingActionBtns = document.querySelectorAll('.listing-action');
        let activeListingBtn = document.querySelector('.listing-action-active')

        listingActionBtns.forEach(function(actionItem){
            actionItem.addEventListener('click', function(e){
                activeListingBtn.classList.remove('listing-action-active');
                e.preventDefault();
                actionItem.classList.toggle('listing-action-active');
                activeListingBtn = actionItem;
            });
        });

        addToCartBtns.forEach(function(category){
            category.addEventListener('click', addToCart)
        });
    </script>
{% endblock javascript %}
    

apeiro_agency/services/templates/services/category_list.html
{% extends "base.html" %}

{% load static %}



{% block content %}
    <div class="container container-w-95 mb-5">
        <div class="page-header bg-warning">
            <div class="page-header--content d-flex justify-content-between align-items-center">
                <div class="page-header--title">
                    <h4 class="text-light">Categories</h4>
                </div>
                <div class="page-header--breadcrumb">
                    <ul class="breadcrumb p-0 m-0 bg-transparent">
                        <li class="breadcrumb-item">
                            <a class="text-light small" href="">Home</a>
                        </li>
                        <li class="breadcrumb-item small">
                            <a class="text-light" href="">Categories</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row" id="categories-section">
            <div class="col-12">
                <!-- listview/gridview/filters -->
                <div class="listing-actions mr-4">
                    <div class="listing-actions--wrapper d-flex justify-content-between align-items-center">
                        <div class="listing-actions--left">
                            <a href="" class="text-dark mr-2 listing-action listing-action-active">
                                <i class="fas fa-th-list"></i>
                            </a>
                            <a href="" class="text-dark listing-action mr-2">
                                <i class="fas fa-th"></i>
                            </a>
                            <span class="text-muted small" id="listing-actions-result-summary">
                                Showing 1–9 of 16 results
                            </span>
                        </div>
                        <div class="listing-actions--right">
                            <form action="">
                                <select name="" id="">
                                    <option value="" selected>select an option</option>
                                    <option value="">Order by A - Z</option>
                                    <option value="">Order by Newest Arrival</option>
                                    <option value="">Order by Most Browsed</option>
                                </select>
                            </form>
                        </div>
                    </div>
                </div>
                
                <!-- category listing and pagination -->
                <div class="row mt-4 categories-row pr-4">
                    
                    {% for category in categories %}
                        <div class="col-sm-12 col-md-4 mb-4">
                            <div class="category-card">
                                <div class="category-card-img">
                                    <img src="{{ category.image.url }}" alt="">
                                </div>
                                <div class="category-card-metadata text-center py-2">
                                    <a class="d-block" href="{{ category.get_absolute_url }}">
                                        <p>{{ category.name }}</p>
                                        <span class="text-muted">$2500</span>
                                    </a>
                                </div>
                                <div class="category-card--actions">
                                    <a href="{{ category.get_absolute_url }}" 
                                        class="btn btn-warning">Details
                                    </a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                    <!-- paginator -->
                    <div class="col-12 mt-5 py-4 top-border-5 border-light 
                        d-flex justify-content-center">
                        <nav aria-label="Page navigation">
                            <ul class="pagination custom-pagination">
                                <li class="page-item">
                                    <a class="page-link" href="#">
                                        <i class="fas fa-long-arrow-alt-left"></i>
                                    </a>
                                </li>
                                <li class="page-item active"><a class="page-link" href="#">1</a></li>
                                <li class="page-item"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item">
                                    <a class="page-link" href="#">
                                        <i class="fas fa-long-arrow-alt-right"></i>
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Footer -->
    <div class="mt-5">
        {% include 'partials/_footer.html' %}
    </div>
{% endblock content %}



{% block javascript %}
    <script>
        const listingActionBtns = document.querySelectorAll('.listing-action');
        let activeListingBtn = document.querySelector('.listing-action-active')

        // table, grid view, range
        listingActionBtns.forEach(function(actionItem){
            actionItem.addEventListener('click', function(e){
                activeListingBtn.classList.remove('listing-action-active');
                e.preventDefault();
                actionItem.classList.toggle('listing-action-active');
                activeListingBtn = actionItem;
            });
        });

        addToCartBtns.forEach(function(category){
            category.addEventListener('click', addToCart)
        });
    </script>
{% endblock javascript %}
    

apeiro_agency/services/templates/services/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <!-- banner part start -->
    <section id="banner_full">
        <div class="banner_item" 
            style="background: url({% static 'images/pexels-fauxels-3184465.jpg' %});">
            <div class="container p-lg-0">
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center">
                        <div class="banner_text">
                            <h1>The New Way To DesignYour Marketing Campaing</h1>
                            <p>Get your design done only based on your needs</p>
                            <a href="#">Learn More</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="banner_item" style="background: url({% static 'images/pexels-fauxels-3228711.jpg' %});">
            <div class="container p-lg-0">
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center">
                        <div class="banner_text">
                            <h1>The New Way To DesignYour Marketing Campaing</h1>
                            <p>Get your design done only based on your needs</p>
                            <a href="#">Learn More</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="banner_item" style="background: url({% static 'images/pexels-fauxels-3184665.jpg' %});">
            <div class="container p-lg-0">
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center">
                        <div class="banner_text">
                            <h1>The New Way To DesignYour Marketing Campaing</h1>
                            <p>Get your design done only based on your needs</p>
                            <a href="#">Learn More</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- banner part end -->

    <!-- Your identity part start -->
    <section id="identity_full">
        <div class="container p-lg-0">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="mt-5">
                        <h2>Browse Our Products</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="catagoys_btn">
                        <ul class="nav mb-3 cl_menu">
                            {% for category in featured_categories %}
                                <li class="nav-item">
                                    <a class="nav-link text-light {% if forloop.counter == 1 %}active{% endif %}"
                                        href="{{ category.get_absolute_url }}">
                                        <img src="{{ category.category_icon.url }}" alt="">
                                    </a>
                                </li>
                            {% endfor %}
                            <li>
                                <a href="{% url 'services:category_list' %}" class="maroff">View More Category</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Your identity part end -->

    <!-- newslatter part start -->
    <section id="newslatter_full">
        <div class="container p-lg-0">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="newaslatter_text">
                        <h4>Join Our Newsletter</h4>
                        <p>Enter your email and be the first to know about special offers, new arrivals and events!</p>
                        <form>
                            <input type="emnail" name="your-email" aria-required="true" placeholder="Enter Your Email">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- news latter part end -->
    
    <!-- Footer -->
    {% include 'partials/_footer.html' %}

{% endblock content %}