apeiro_agency/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path(
        "",
        views.home_page_view,
        name="home",
    ),
    path(
        "categories/",
        views.category_list_view,
        name='category_list'
    ),
    path(
        "category/<slug:slug>/",
        views.category_detail_view,
        name='category_detail'
    )
]

apeiro_agency/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.add_to_basket,
        name='add_to_basket'
    ),
    path('cart/', views.manage_basket,
        name='cart'
    ),
]

apeiro_agency/services/urls.py
from django.urls import path
from . import views

app_name = 'services'

urlpatterns = [
    path(
        "",
        views.home_page_view,
        name="home",
    ),
    path(
        "categories/",
        views.category_list_view,
        name='category_list'
    ),
    path(
        "services/",
        views.service_list_view,
        name='service_list'
    ),
    path(
        "services/<slug:category>/",
        views.service_list_view,
        name='category_service_list'
    ),
]

apeiro_agency/users/urls.py
from django.urls import path

from apeiro_agency.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    path("",
        include("services.urls", namespace='services')
    ),
    # User management
    path(
        "users/",
        include("apeiro_agency.users.urls", namespace="users"),
    ),
    path('orders/', include('orders.urls', namespace='orders')),
    path("accounts/", include("allauth.urls")),
    path('api-auth/', include('rest_framework.urls')),
    path('api/services/', include('services.api_routes')),
    path('api/orders/', include('orders.api_routes')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns

apeiro_agency/core/models.py
from model_utils.models import TimeStampedModel

from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class PricingPlan(TimeStampedModel):
    title = models.CharField(max_length=50)
    monthly_price = models.PositiveIntegerField(
        blank=True,
        null=True
    )
    annual_price = models.PositiveIntegerField(
        blank=True,
        null=True
    )
    ontime_pay = models.PositiveIntegerField(
        blank=True,
        null=True
    )

    class Meta:
        ordering = ('title',)

    def __str__(self):
        s = f'{self.title}, '
        if self.monthly_price:
            s += f'monthly: {self.monthly_price} '
        if self.annual_price:
            s += f'annual: {self.annual_price} '
        if self.ontime_pay:
            s += f'onetime: {self.ontime_pay}'
        return s.strip()


class FeatureItem(TimeStampedModel):
    feature_key = models.CharField(max_length=200)
    feature = models.CharField(max_length=200)

    class Meta:
        ordering = ('feature_key',)

    def __str__(self):
        return f'{self.feature_key} : {self.feature}'

apeiro_agency/orders/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.conf import settings

from services.models import Service


class Basket(models.Model):
    OPEN = 10
    SUBMITTED = 20
    STATUSES = (
        (OPEN, "Open"),
        (SUBMITTED, "Submitted")
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )
    status = models.IntegerField(
        choices=STATUSES,
        default=OPEN
    )

    def is_empty(self):
        return self.basketlines.all().count() == 0

    def count(self):
        return sum(i.quantity for i in self.basketlines.all())


class BasketLine(models.Model):
    basket = models.ForeignKey(
        Basket,
        on_delete=models.CASCADE,
        related_name='basketlines'
    )
    service = models.ForeignKey(
        Service,
        on_delete=models.CASCADE
    )
    quantity = models.PositiveIntegerField(
        default=1,
        validators=[MinValueValidator(1)]
    )

apeiro_agency/service_analytics/models.py
from model_utils.models import TimeStampedModel

from django.db import models
from django.conf import settings


class Impression(TimeStampedModel):
    interested_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank=True
    )
    service = models.ForeignKey(
        "services.Service",
        on_delete=models.CASCADE,
        related_name='impressions'
    )
    count = models.BigIntegerField(default=0)


class Rating(TimeStampedModel):
    RATING_VALUES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5')
    ) 
    service = models.ForeignKey(
        "services.Service",
        on_delete=models.CASCADE,
        related_name='ratings'
    )
    value = models.SmallIntegerField(choices=RATING_VALUES)
    customer = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )


class Sell(TimeStampedModel):
    service = models.ForeignKey(
        "services.Service",
        on_delete=models.CASCADE,
        related_name='sells'
    )
    customer = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='purchases'
    )

apeiro_agency/services/models.py
from model_utils.models import TimeStampedModel

from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

from core.models import FeatureItem, PricingPlan
from service_analytics.models import Impression


class ServiceCategory(TimeStampedModel):
    name = models.CharField(max_length=100, unique=True)
    category_icon = models.ImageField(
        upload_to='category_icons/',
        blank=True,
        default='category_icons/default.png'
    )
    image = models.ImageField(
        upload_to='category/',
        blank=True,
        default='category/default.jpg'
    )
    slug = models.SlugField(blank=True, null=True, unique=True)
    description = models.TextField(blank=True, null=True)
    is_featured = models.BooleanField(default=False)

    class Meta:
        ordering = ['name', '-created']
        verbose_name_plural = 'Service Categories'
    
    def get_absolute_url(self):
        return reverse(
            'services:category_service_list',
            args=(),
            kwargs={'slug': self.slug}
        )    
    
    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        update = kwargs.get('update', False)
        if not update:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class Service(TimeStampedModel):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(blank=True, null=True, unique=True)
    primary_image = models.ImageField(
        upload_to='services/primary-images/',
        blank=True,
        default='services/primary-images/default.jpg'
    )
    description = models.TextField(blank=True, null=True)
    vendor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='services',
        on_delete=models.CASCADE
    )
    features = models.ManyToManyField(
        FeatureItem,
        blank=True
    )
    pricing = models.ForeignKey(
        PricingPlan,
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )
    category = models.ForeignKey(
        ServiceCategory,
        on_delete=models.CASCADE,
        related_name='services'
    )
    is_verified = models.BooleanField(default=False)

    class Meta:
        ordering = ['name', '-created']
        verbose_name_plural = 'Services'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        update = kwargs.get('update', False)
        if not update:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class ServicePhoto(TimeStampedModel):
    image = models.ImageField(upload_to='services/images/')
    service = models.ForeignKey(Service,
        related_name='images',
        on_delete=models.CASCADE
    )

apeiro_agency/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name Do Not Cover Name Patterns
    # Around the Globe.
    name = models.CharField(
        _("Name of User"), blank=True, max_length=255
    )

    def get_absolute_url(self):
        return reverse(
            "users:detail", kwargs={"username": self.username}
        )

apeiro_agency/orders/forms.py
from django.forms import inlineformset_factory
from .models import Basket, BasketLine


basketline_formset = inlineformset_factory(
    Basket,
    BasketLine,
    fields=('quantity',),
    extra=0
)

apeiro_agency/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {
            "duplicate_username": _(
                "This username has already been taken."
            )
        }
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(
            self.error_messages["duplicate_username"]
        )

apeiro_agency/core/views.py
from django.shortcuts import render
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView
)

from .models import ServiceCategory


class HomePageView(TemplateView):
    template_name = 'core/home.html'

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        featured_categories = ServiceCategory.objects.filter(
            is_featured=True
        )
        ctx['featured_categories'] = featured_categories
        return ctx

home_page_view = HomePageView.as_view()


class CategoryListView(ListView):
    model = ServiceCategory
    template_name = 'core/category_list.html'
    context_object_name = 'categories'

category_list_view = CategoryListView.as_view()


class CategoryDetailView(DetailView):
    model = ServiceCategory
    template_name = 'core/category_detail.html'
    context_object_name = 'category'
    slug_field = 'slug' 
    slug_url_kwarg = 'slug' 

category_detail_view = CategoryDetailView.as_view()

apeiro_agency/orders/views.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from django.urls import reverse
from services.models import Service
from .models import Basket, BasketLine
from .forms import basketline_formset


def add_to_basket(request):
    service = get_object_or_404(
        Service, pk=request.GET.get('service_id')
    )
    basket = request.basket
    if not request.basket:
        if request.user.is_authenticated:
            user = request.user
        else:
            user = None
        basket = Basket.objects.create(
            user=user,
        )
        request.session['basket_id'] = basket.id
    basketline, created = BasketLine.objects.get_or_create(
        basket=basket, service=service
    )   

    if not created:
        basketline.quantity = 1
        basketline.save()
    return JsonResponse({'status': 1})


def manage_basket(request):
    if not request.basket or request.basket.is_empty():
        return render(request, 'orders/basket.html', {'formset': None})
    
    if request.method == 'POST':
        formset = basketline_formset(
            request.POST, instance=request.basket,
        )
        if formset.is_valid():
            formset.save()
    else:
        formset = basketline_formset(
            instance=request.basket,
        )
    
    return  render(request, 'orders/basket.html', {'formset': formset})

apeiro_agency/service_analytics/views.py
from django.shortcuts import render

# Create your views here.

apeiro_agency/services/views.py
from django.db.models import Count
from django.shortcuts import render, get_object_or_404
from django.views.generic.base import TemplateResponseMixin, View
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView
)

from .models import ServiceCategory, Service


class HomePageView(TemplateView):
    template_name = 'services/home.html'

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        featured_categories = ServiceCategory.objects.filter(
            is_featured=True
        )
        ctx['featured_categories'] = featured_categories
        return ctx

home_page_view = HomePageView.as_view()


class ServiceListView(TemplateResponseMixin, View):
    model = Service
    template_name = 'services/products.html'

    def get(self, request, category=None):
        categories = ServiceCategory.objects.annotate(
            total_services=Count('services'))
        services = Service.objects.all()

        if category:
            category = get_object_or_404(ServiceCategory, slug=category)
            services = services.filter(category=category)
        return self.render_to_response({
            'categories': categories,
            'category': category,
            'services': services
        })

service_list_view = ServiceListView.as_view()

class CategoryListView(ListView):
    model = ServiceCategory
    template_name = 'services/category_list.html'
    context_object_name = 'categories'

category_list_view = CategoryListView.as_view()


class CategoryDetailView(DetailView):
    model = ServiceCategory
    template_name = 'services/category_detail.html'
    context_object_name = 'category'
    slug_field = 'slug' 
    slug_url_kwarg = 'slug' 

category_detail_view = CategoryDetailView.as_view()

apeiro_agency/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import (
    DetailView,
    RedirectView,
    UpdateView,
)
from django.conf import settings

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These Next Two Lines Tell the View to Index
    #   Lookups by Username
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):
    fields = [
        "name",
    ]

    # We already imported user in the View code above,
    #   remember?
    model = User

    # Send the User Back to Their Own Page after a
    #   successful Update
    def get_success_url(self):
        return reverse(
            "users:detail",
            kwargs={'username': self.request.user.username},
        )

    def get_object(self):
        # Only Get the User Record for the
        #   User Making the Request
        return User.objects.get(
            username=self.request.user.username
        )


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse(
            "users:detail",
            kwargs={"username": self.request.user.username},
        )


user_redirect_view = UserRedirectView.as_view()

apeiro_agency/templates/partials/_footer.html
{% load static %}
<!-- contact part start -->
<section id="contact_full" class="bg-dark text-light">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="contactp1">
                    <a href="#"><img src="{% static 'images/logo-2.png' %}" alt=""></a>
                    <p>Lorem Ipsum is simply dummy text of the printing and typeset ing industry.</p>
                    <div class="social_icon">
                        <a href="#"><i class="fab fa-facebook-f"></i></a>
                        <a href="#"><i class="fab fa-twitter"></i></a>
                        <a href="#"><i class="fab fa-instagram"></i></a>
                        <a href=""><i class="fab fa-pinterest-p"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-3">
                <div class="contactp2">
                    <h6>Customer Services</h6>
                    <ul>
                        <li><a href="{% url 'account_signup' %}">Register</a></li>
                        <li><a href="{% url 'account_login' %}">Login</a></li>
                        <li><a href="#">Track Order</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3">
                <div class="contactp2">
                    <h6>FAQ</h6>
                    <ul>
                        <li><a href="#">Ordering Info</a></li>
                        <li><a href="#">Shipping & Dealivery</a></li>
                        <li><a href="#">Our Service</a></li>
                        <li><a href="#">Pricing Tables</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3">
                <div class="contactp3">
                    <h6>Contact Us</h6>
                    <ul>
                        <li>94 Stockman Drive</li>
                        <li>Phone: +880 123 456 7890</li>
                        <li>Email:youremail@gmail.com</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- contact part end -->

apeiro_agency/templates/partials/_navbar.html
{% load static %}

<!-- header part start -->
<nav class="navbar navbar-expand-lg main_menu">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon">
                <i class=" fas fa-bars"></i>
            </span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav mr-auto navbar-left">
                <li class="nav-item active">
                    <a class="nav-link active" href="{% url 'services:home' %}">
                        Home <span class="sr-only">(current)</span>
                    </a>
                </li>
                <div class="nav-item">
                    <a class="nav-link" href="{% url 'services:service_list' %}">
                        Products
                    </a>
                </div>
            </ul>
            <ul class="nav navbar-nav navbar-right align-items-center">
                <li>
                    <div class="cart mr-2">
                        <a class="text-dark" href="{% url 'orders:cart' %}">
                            <i class="fas fa-shopping-cart mr-0"></i>
                        </a>
                        
                        {% if request.basket %}
                            <div class="cartcount">
                                <a class="text-light" href="{% url 'orders:cart' %}">
                                <sup>
                                    <span class="badge badge-danger cartcount-number">
                                        {{ request.basket.count }}
                                    </span>
                                </sup>
                                </a>
                            </div>
                        {% else %}
                            <a href="{% url 'orders:cart' %}">
                                <span class="badge badge-danger cartcount-number">
                                    0
                                </span>
                            </a>
                        {% endif %}
                    </div>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item dropdown account-dropdown">
                        <a class="nav-link dropdown-toggle account" href="#" 
                            id="accountDropdown" role="button" data-toggle="dropdown" 
                            aria-haspopup="true" aria-expanded="false">
                            <i class="far fa-user-circle fa-2x"></i>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="accountDropdown">
                            <a class="dropdown-item" 
                                href="{% url 'users:detail' request.user.username  %}">
                                My Account
                            </a>
                            <a class="dropdown-item" href="#">My Orders</a>
                        <div class="dropdown-divider"></div>
                            <a class="dropdown-item" 
                                href="{% url 'account_logout' %}">
                                Logout
                            </a>
                        </div>
                    </li>
                    {% comment %}
                    {% else %}
                        <li class="nav-item">
                            {# URL provided by django-allauth/account/urls.py #}
                            <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
                        </li>
                        <li class="nav-item">
                            {# URL provided by django-allauth/account/urls.py #}
                            <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
                        </li> 
                    {% endcomment %}
                {% endif %}
                <li>
                    <a href="#"><i class="fab fa-facebook-f s_icon"></i></a>
                </li>
                <li>
                    <a href="#"><i class="fab fa-twitter s_icon"></i></a>
                </li>
                <li>
                    <a href="#"><i class="fab fa-instagram s_icon"></i></a>
                </li>
                <li>
                    <a href="#"><i class="fab fa-pinterest-p s_icon"></i></i></a>
                </li>
            </ul>
        </div>
        <a class="navbar-brand" href="{% url 'services:home' %}">
            <img src="{% static 'images/logo-2-768x296.png' %}" class="w-100" alt="logo">
        </a>
    </div>
</nav>
<!-- header part end -->